### ISSUE TITLE
About screen (and other screens as well)

### ISSUE THREAD

**Issue by Lolimipsu** [Takagi-san-VN-Development-Team/tkvn-site#3]
I was hoping we could make it something like this.
I already have the template of the about screen, it just needs some reworks
![image](https://user-images.githubusercontent.com/44487404/102682376-066c5f00-4204-11eb-808b-0621d0866f1e.png)

**Comment by hachiXhachi** [comment]
[tkvn-site-main-hachi.zip](https://github.com/Takagi-san-VN-Development-Team/tkvn-site/files/5729564/tkvn-site-main-hachi.zip)
here is the one i make

**Comment by Lolimipsu** [comment]
merged with master
